services:
  server:
    build:
      context: .
    container_name: server
    restart: always
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: always
    ports: 
      - "8000:8000"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - server

volumes:
  static_volume:
  media_volume: