services:
  server:
    build:
      context: .
    container_name: server
    restart: always
    volumes:
      - ./frobshop:/app
      - static_volume:/app/static_root
      - media_volume:/app/media
    expose:
      - "8000"
    command: gunicorn frobshop.wsgi --bind 0.0.0.0:8000
    
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static_root
      - media_volume:/home/app/media
    depends_on:
      - server

volumes:
  static_volume:
  media_volume: