name: CI & CD for shop
on: ['push']

jobs:
    simple_CI:
      name: Django CI
      runs-on: ubuntu-latest
      steps:
          - name: testing purpose
            run: echo "B"
          # - name: Checkout code
          #   uses: actions/checkout@v4
          # - name: up the container
          #   run: docker-compose up -d
          # - name: run tests
          #   run:  docker exec server bash -c "python3 manage.py test"
    simple_CD:
      name: Django CD
      needs:
        - simple_CI
      runs-on: ubuntu-latest
      steps:
        - name: Configure SSH
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVET_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USER: ${{ secrets.SSH_USER }}
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
            chmod 600 ~/.ssh/github
            cat >>~/.ssh/config <<END
            Host target
              HostName $SSH_HOST
              USER $SSH_USER
              IdentityFile ~/.ssh/github
              LogLevel ERROR
              StrictHostKeyChecking no
            END
        - name: Run Deploy
          run: |
            ssh target "cd test-ci-cd && docker-compose down && git pull && docker-compose build && docker-compose up -d --forece-recreate"

      